# Generated by Django 2.2 on 2019-12-15 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matchId', models.IntegerField()),
                ('match', models.CharField(max_length=10)),
                ('round', models.CharField(max_length=10)),
                ('time', models.DateField()),
                ('hostTeam', models.CharField(max_length=20)),
                ('guestTeam', models.CharField(max_length=20)),
                ('result', models.CharField(max_length=10)),
                ('company', models.CharField(max_length=10)),
                ('upperStage', models.FloatField()),
                ('lowerStage', models.FloatField()),
                ('opening', models.CharField(max_length=20)),
                ('win', models.FloatField()),
                ('peace', models.FloatField()),
                ('lose', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='BigOrSmall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=10)),
                ('immediateUpperStage', models.FloatField()),
                ('immediateLowerStage', models.FloatField()),
                ('immediateOpening', models.CharField(max_length=20)),
                ('startUpperStage', models.FloatField()),
                ('startLowerStage', models.FloatField()),
                ('startOpening', models.CharField(max_length=20)),
                ('subMatchId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Historical.History')),
            ],
        ),
    ]
