# Generated by Django 2.2 on 2019-12-24 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('matchId', models.IntegerField(primary_key=True, serialize=False)),
                ('match', models.CharField(max_length=10)),
                ('round', models.CharField(max_length=10)),
                ('time', models.DateField()),
                ('match_time', models.CharField(max_length=16)),
                ('hostTeam', models.CharField(max_length=16)),
                ('guestTeam', models.CharField(max_length=16)),
                ('result', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='European',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=8)),
                ('immediateWin', models.FloatField()),
                ('immediatePeace', models.FloatField()),
                ('immediateLose', models.FloatField()),
                ('startWin', models.FloatField()),
                ('startPeace', models.FloatField()),
                ('startLose', models.FloatField()),
                ('subMatchId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Historical.History')),
            ],
        ),
        migrations.CreateModel(
            name='BigOrSmall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=8)),
                ('immediateUpperStage', models.FloatField()),
                ('immediateLowerStage', models.FloatField()),
                ('immediateOpening', models.CharField(max_length=20)),
                ('startUpperStage', models.FloatField()),
                ('startLowerStage', models.FloatField()),
                ('startOpening', models.CharField(max_length=20)),
                ('changedTime', models.CharField(max_length=12)),
                ('startTime', models.CharField(max_length=12)),
                ('subMatchId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Historical.History')),
            ],
        ),
        migrations.CreateModel(
            name='Asia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=8)),
                ('immediateUpperStage', models.FloatField()),
                ('immediateLowerStage', models.FloatField()),
                ('immediateOpening', models.CharField(max_length=20)),
                ('startUpperStage', models.FloatField()),
                ('startLowerStage', models.FloatField()),
                ('startOpening', models.CharField(max_length=20)),
                ('changedTime', models.CharField(max_length=12)),
                ('startTime', models.CharField(max_length=12)),
                ('subMatchId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Historical.History')),
            ],
        ),
    ]
